# Дубликаты, пропуски и неинформативные данные. Практическая работа

## Задача

В этой практической работе вы продолжите заполнять пропущенные значения в некоторых переменных в данных о подержанных автомобилях.

Напомним, что вы работаете с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.

## Описание датасета:
- `id`: идентификатор записи;
- `url`: URL записи о продаже;
- `region`: регион;
- `region_url`: URL региона;
- `price`: стоимость;
- `year`: год выпуска;
- `manufacturer`: производитель;
- `model`: модель;
- `condition`: состояние;
- `cylinders`: количество цилиндров;
- `fuel`: тип топлива;
- `odometer`: количество пройденных миль;
- `title_status`: статус;
- `transmission`: коробка передач;
- `VIN`: идентификационный номер;
- `drive`: тип привода;
- `size`: размер;
- `type`: кузов;
- `paint_color`: цвет;
- `image_url`: URL изображения;
- `description`: указанное описание;
- `county`: страна;
- `state`: штат;
- `lat`: широта;
- `long`: долгота;
- `posting_date`: дата размещения объявления о продаже;
- `price_category`: категория цены.

In [ ]:
# Импортируйте необходимые библиотеки

### Задача 1. Загрузка датасета и ознакомление с количеством пропущенных значений

1. Загрузите датасет из `df_clean.csv` и выведите первые пять записей.

In [1]:
# Ваш код здесь
import pandas as pd

In [2]:
df = pd.read_csv('data/df_clean.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442.0,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023.0,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048.0,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291.0,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000.0,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium

2. Выведите количество полностью заполненных объектов и их процент из всей выборки. Воспользуйтесь материалами из видео.

In [3]:
# Ваш код здесь
def print_useful_rows_info(df):
    print('Количество полностью заполненных объектов из всей выборки:', len(df.dropna()))
    print('Процент полностью заполненных объектов из всей выборки:', round(len(df.dropna()) / len(df) * 100, 2))
    
print_useful_rows_info(df)

Количество полностью заполненных объектов из всей выборки: 9507
Процент полностью заполненных объектов из всей выборки: 95.07

In [4]:
len(df.dropna())

9507

In [5]:
len(df)

10000

3. Сохраните в переменную и выведите процент пропущенных значений для каждого признака, отсортируйте признаки по убыванию процента пропущенных значений. Воспользуйтесь материалами из видео и не забудьте передать верный параметр сортировки.

In [7]:
# Ваш код здесь
missing_values = ((df.isna().sum() / len(df)) * 100).sort_values(ascending=False)
print('Процент пропущенных значений:\n', missing_values)

Процент пропущенных значений:
 title_status      1.66
model             1.28
long              0.98
lat               0.98
fuel              0.63
transmission      0.45
year              0.36
image_url         0.02
posting_date      0.02
description       0.02
id                0.00
state             0.00
odometer          0.00
url               0.00
manufacturer      0.00
price             0.00
region_url        0.00
region            0.00
price_category    0.00
dtype: float64

4. Выведите список всех признаков, в которых имеются пропущенные значения. Воспользуйтесь результатом вывода предыдущего шага, чтобы отсортировать признаки, подходящие под условие.

In [8]:
# Ваш код здесь
missing_columns = missing_values[missing_values.values > 0].index.tolist()
missing_columns

['title_status',
 'model',
 'long',
 'lat',
 'fuel',
 'transmission',
 'year',
 'image_url',
 'posting_date',
 'description']

### Задача 2. Обработка пропусков в дате размещения объявления о продаже
1. Выведите количество значений для даты размещения объявления о продаже, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [9]:
# Ваш код здесь
df.posting_date.value_counts(dropna=False)

2021-04-19T10:00:54-0400    2
2021-04-13T09:11:02-0500    2
2021-04-11T11:11:05-0400    2
2021-04-08T10:06:02-0500    2
2021-04-29T21:11:29-0400    2
                           ..
2021-04-05T18:13:07-0400    1
2021-04-26T13:32:07-0400    1
2021-05-04T14:01:18-0400    1
2021-04-24T11:40:55-0700    1
2021-04-24T13:50:49-0400    1
Name: posting_date, Length: 9958, dtype: int64

2. Выведите описательные статистики даты размещения объявления о продаже. Обратите внимание, что на месте самой популярной даты может стоять любое из значений, которое встречается два раза.

In [10]:
# Ваш код здесь
df.posting_date.describe()

count                         9998
unique                        9957
top       2021-04-19T10:00:54-0400
freq                             2
Name: posting_date, dtype: object

3. Выведите записи, в которых дата размещения объявления о продаже не заполнена. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [11]:
# Ваш код здесь
df[df.posting_date.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
6728,7315259025,https://nh.craigslist.org/cto/d/manchester-201...,new hampshire,https://nh.craigslist.org,3750,NaN,other,NaN,NaN,95674.0,NaN,NaN,NaN,NaN,nh,NaN,NaN,NaN,low
9388,7208549803,https://bellingham.craigslist.org/ctd/d/bellin...,bellingham,https://bellingham.craigslist.org,11999,NaN,other,NaN,NaN,95674.0,NaN,NaN,NaN,NaN,wa,NaN,NaN,NaN,medium

4. Обработайте пропуски, удалив записи, в которых дата размещения объявления о продаже не заполнена, и сохраните обновлённый датафрейм.

In [12]:
# Ваш код здесь
df = df[df.posting_date.notna()]

In [13]:
len(df.dropna())

9507

In [14]:
len(df) #'проверяю для себя, точно ли удалил'

9998

In [15]:
print_useful_rows_info(df)

Количество полностью заполненных объектов из всей выборки: 9507
Процент полностью заполненных объектов из всей выборки: 95.09

5. Выведите для обновлённого датафрейма количество пропущенных значений в дате размещения объявления о продаже.

In [16]:
# Допишите код
print("Количество пропущенных значений в posting_date:", df.posting_date.isna().sum())

Количество пропущенных значений в posting_date: 0

### Задача 3. Обработка пропусков в коробке передач
1. Выведите количество значений для коробки передач, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [17]:
# Ваш код здесь
df.transmission.value_counts(dropna=False)

automatic    7700
other        1624
manual        631
NaN            43
Name: transmission, dtype: int64

2. Выведите описательные статистики коробки передач.

In [18]:
# Ваш код здесь
df.transmission.describe()

count          9955
unique            3
top       automatic
freq           7700
Name: transmission, dtype: object

3. Выведите записи, в которых коробка передач не заполнена. Посмотрите на данные и подумайте, какую стратегию обработки значений можно применить.

In [19]:
# Ваш код здесь
df[df.transmission.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
111,7305109580,https://grandrapids.craigslist.org/ctd/d/comst...,grand rapids,https://grandrapids.craigslist.org,12750,2013.0,lexus,es,gas,109382.0,clean,NaN,https://images.craigslist.org/00n0n_kACT1l7OCN...,2013 Lexus ES 350 4dr Sdn Offered by: Auto...,mi,43.059210,-85.688970,2021-04-11T09:41:58-0400,medium
112,7314951119,https://southjersey.craigslist.org/ctd/d/chest...,south jersey,https://southjersey.craigslist.org,18199,2012.0,jeep,wrangler,other,130174.0,clean,NaN,https://images.craigslist.org/00I0I_gRmuXmqil1...,2012 Jeep Wrangler Unlimited Sport 4WD Off...,nj,40.135190,-74.703570,2021-04-30T14:58:56-0400,medium
817,7308021604,https://southjersey.craigslist.org/ctd/d/maple...,south jersey,https://southjersey.craigslist.org,11999,2015.0,honda,civic,gas,79797.0,clean,NaN,https://images.craigslist.org/00b0b_aCqgRZ7sAx...,2015 Honda Civic EX Offered by: VIP Auto O...,nj,39.938023,-74.971461,2021-04-16T19:46:55-0400,medium
931,7314781483,https://nh.craigslist.org/ctd/d/plaistow-2018-...,new hampshire,https://nh.craigslist.org,64990,2018.0,ram,3500,other,8853.0,clean,NaN,https://images.craigslist.org/00000_iHpXs2BVmN...,2018 RAM Ram Chassis 3500 Short Wheelbase (Dua...,nh,42.834977,-71.107791,2021-04-30T10:15:30-0400,high
970,7315044723,https://poconos.craigslist.org/ctd/d/chesterfi...,poconos,https://poconos.craigslist.org,22699,2014.0,jeep,wrangler,gas,110493.0,clean,NaN,https://images.craigslist.org/00M0M_aFDXWIfug9...,2014 Jeep Wrangler Unlimited Sport 4WD Off...,pa,40.135190,-74.703570,2021-04-30T17:46:04-0400,high
1156,7311083008,https://greenville.craigslist.org/ctd/d/greenv...,greenville / upstate,https://greenville.craigslist.org,9998,2013.0,volkswagen,jetta,diesel,96115.0,clean,NaN,https://images.craigslist.org/00F0F_9oq0KNmZIM...,2013 VOLKSWAGEN JETTA TDI Highline Offered...,sc,34.832550,-82.368350,2021-04-22T17:55:57-0400,medium
1349,7303942891,https://wenatchee.craigslist.org/ctd/d/everett...,wenatchee,https://wenatchee.craigslist.org,4995,2005.0,honda,pilot,gas,261591.0,clean,NaN,https://images.craigslist.org/00S0S_aASnH27HDH...,2005 Honda Pilot EX Offered by: Corn Motor...,wa,47.912956,-122.235725,2021-04-08T16:52:48-0700,low
1715,7310344536,https://roanoke.craigslist.org/ctd/d/roanoke-2...,roanoke,https://roanoke.craigslist.org,3995,2007.0,ford,mustang,gas,159342.0,clean,NaN,https://images.craigslist.org/00J0J_6BuTyEWqNQ...,2007 Ford Mustang V6 Deluxe Coupe Offered ...,va,37.335355,-79.859385,2021-04-21T11:30:46-0400,low
1914,7307857568,https://fortmyers.craigslist.org/lee/ctd/d/for...,ft myers / SW florida,https://fortmyers.craigslist.org,17000,2012.0,jeep,grand cherokee,gas,116079.0,clean,NaN,https://images.craigslist.org/00000_gqxck1dkEu...,2012 Jeep Grand Cherokee Limited Offered b...,fl,26.498960,-81.819380,2021-04-16T14:46:41-0400,medium
2023,7314592581,https://pueblo.craigslist.org/ctd/d/pueblo-200...,pueblo,https://pueblo.craigslist.org,8494,2004.0,ford,ranger,gas,156969.0,clean,NaN,https://images.craigslist.org/01212_6ixSUy4WCq...,2004 Ford Ranger Offered by: Discount Moto...,co,38.298339,-104.616024,2021-04-29T17:30:13-0600,low
2072,7307459834,https://tallahassee.craigslist.org/ctd/d/ocala...,tallahassee,https://tallahassee.craigslist.org,22900,2013.0,ford,f-450,other,225804.0,clean,NaN,https://images.craigslist.org/00Y0Y_73hcVVn32A...,2013 Ford F-450 Super Duty 4X2 4dr SuperCab 16...,fl,29.230860,-82.149150,2021-04-15T18:47:10-0400,high
2078,7314485544,https://stlouis.craigslist.org/ctd/d/saint-pet...,"st louis, MO",https://stlouis.craigslist.org,15891,2019.0,nissan,sentra,gas,90811.0,clean,NaN,https://images.craigslist.org/00T0T_2tloqlG3YB...,2019 Nissan Sentra SV Offered by: Auto Pla...,il,38.802269,-90.673649,2021-04-29T14:55:20-0500,medium
2129,7302733118,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,14700,2016.0,ford,fusion,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00O0O_fkFRDDi4yq...,Car Starz Call Sales at 717-401-4221 2016 Ford...,pa,41.261540,-78.704520,2021-04-06T14:39:29-0400,medium
2627,7314386590,https://roanoke.craigslist.org/ctd/d/roanoke-2...,roanoke,https://roanoke.craigslist.org,7995,2013.0,nissan,altima,gas,87004.0,clean,NaN,https://images.craigslist.org/00E0E_T1UmvdZBIq...,2013 Nissan Altima 2.5 SL Offered by: Blue...,va,37.335355,-79.859385,2021-04-29T13:05:26-0400,low
3192,7307686006,https://cincinnati.craigslist.org/ctd/d/newpor...,cincinnati,https://cincinnati.craigslist.org,7995,2012.0,chevrolet,volt,hybrid,72205.0,clean,NaN,https://images.craigslist.org/00Y0Y_l66xSh7dIq...,2012 Chevrolet Chevy Volt Premium Offered ...,oh,39.002570,-84.423424,2021-04-16T10:31:31-0400,low
3551,7310989457,https://oklahomacity.craigslist.org/ctd/d/fort...,oklahoma city,https://oklahomacity.craigslist.org,10495,2016.0,subaru,outback,gas,205315.0,clean,NaN,https://images.craigslist.org/00909_iyoxNVG6Hv...,Se Habla Español! This GORGEOUS Subaru Outback...,ok,39.029900,-96.839600,2021-04-22T14:06:51-0500,medium
3814,7314143519,https://boise.craigslist.org/ctd/d/nampa-1971-...,boise,https://boise.craigslist.org,10395,1971.0,other,American LaFrance Fire Truck,NaN,78974.0,clean,NaN,https://images.craigslist.org/00909_aLVPntLOWj...,"1971 American LaFrance Fire Truck - $10,395....",id,43.593700,-116.536000,2021-04-28T19:02:38-0600,medium
3821,7314284239,https://gainesville.craigslist.org/ctd/d/kissi...,gainesville,https://gainesville.craigslist.org,12600,2012.0,lexus,is,gas,119123.0,clean,NaN,https://images.craigslist.org/00a0a_iLNqrX7M6C...,2012 Lexus IS 250 RWD Offered by: WE ARE O...,fl,28.329026,-81.404237,2021-04-29T10:05:17-0400,medium
3938,7313340095,https://flint.craigslist.org/ctd/d/burton-2018...,flint,https://flint.craigslist.org,8999,2018.0,nissan,sentra,gas,100502.0,clean,NaN,https://images.craigslist.org/01313_1Otgvohan8...,2018 NISSAN SENTRA SV Offered by: Tom's Di...,mi,43.004529,-83.635055,2021-04-27T11:36:15-0400,low
4087,7309751102,https://providence.craigslist.org/ctd/d/hookse...,rhode island,https://providence.craigslist.org,29888,2015.0,jeep,wrangler,gas,79873.0,clean,NaN,https://images.craigslist.org/00r0r_3nZoSFWLjf...,2015 Jeep Wrangler Rubicon 4WD Offered by:...,ri,43.066264,-71.447000,2021-04-20T09:32:59-0400,high
5081,7316685506,https://tampa.craigslist.org/hil/ctd/d/brandon...,tampa bay area,https://tampa.craigslist.org,16991,2016.0,ford,mustang,gas,81028.0,clean,NaN,https://images.craigslist.org/00q0q_ff4BI4TwI4...,2016 Ford Mustang EcoBoost Offered by: Bra...,fl,27.946392,-82.342089,2021-05-04T10:01:03-0400,medium
5260,7307388962,https://medford.craigslist.org/ctd/d/medford-2...,medford-ashland,https://medford.craigslist.org,14984,2010.0,ford,expedition,NaN,128975.0,NaN,NaN,https://images.craigslist.org/00B0B_aSYu1CvWOQ...,2010 Ford Expedition Eddie Bauer Sport Utility...,or,42.329925,-122.875811,2021-04-15T13:28:27-0700,medium
5320,7315518091,https://inlandempire.craigslist.org/ctd/d/font...,inland empire,https://inlandempire.craigslist.org,20775,2012.0,gmc,yukon,gas,104908.0,clean,NaN,https://images.craigslist.org/00y0y_jYD9hosoC3...,2012 GMC Yukon SLT Offered by: R & B AUTOS...,ca,34.107223,-117.455322,2021-05-01T14:30:28-0700,medium
5475,7303944212,https://yakima.craigslist.org/ctd/d/everett-20...,yakima,https://yakima.craigslist.org,7995,2013.0,dodge,grand caravan,gas,144401.0,clean,NaN,https://images.craigslist.org/00e0e_gr1IsBb5XA...,2013 Dodge Grand Caravan SE Offered by: Co...,wa,47.912956,-122.235725,2021-04-08T16:56:02-0700,low
5491,7302829978,https://greenville.craigslist.org/ctd/d/greenv...,greenville / upstate,https://greenville.craigslist.org,12988,2016.0,jeep,compass,gas,129674.0,clean,NaN,https://images.craigslist.org/00d0d_lHeM5HIRyZ...,2016 JEEP COMPASS 4X4 LATITUDE Offered by:...,sc,34.801450,-82.426210,2021-04-06T17:21:49-0400,medium
6172,7305971655,https://lancaster.craigslist.org/ctd/d/brockpo...,lancaster,https://lancaster.craigslist.org,7600,2012.0,jeep,patriot,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00909_hw8K8SHtsk...,Car Starz Call Sales at 717-401-4221 2012 Jeep...,pa,41.261540,-78.704520,2021-04-12T21:08:22-0400,low
6682,7303882218,https://chico.craigslist.org/ctd/d/sacramento-...,chico,https://chico.craigslist.org,27995,2018.0,ford,f-150,gas,72005.0,clean,NaN,https://images.craigslist.org/00Z0Z_eRA2RnvAhM...,2018 Ford F-150 F150 F 150 XL 2WD SuperCrew 5....,ca,38.611927,-121.423118,2021-04-08T14:42:05-0700,high
6757,7308278778,https://lincoln.craigslist.org/ctd/d/fort-rile...,lincoln,https://lincoln.craigslist.org,17495,2013.0,jeep,grand cherokee,gas,119275.0,clean,NaN,https://images.craigslist.org/00z0z_hH9cJEl2uw...,Se Habla Español! This GORGEOUS Jeep Grand Che...,ne,39.029900,-96.839600,2021-04-17T11:07:19-0500,medium
6817,7310860252,https://charlotte.craigslist.org/ctd/d/greensb...,charlotte,https://charlotte.craigslist.org,6998,2008.0,honda,civic cpe,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00l0l_3evmKC5YBJ...,2008 Honda Civic Cpe 2dr Auto EX-L Oak Ridge ...,nc,36.129540,-79.957520,2021-04-22T11:41:26-0400,low
6851,7312392950,https://stlouis.craigslist.org/ctd/d/saint-pet...,"st louis, MO",https://stlouis.craigslist.org,24995,2015.0,ford,explorer,gas,101241.0,clean,NaN,https://images.craigslist.org/00B0B_e2X7o0yUFs...,2015 Ford Explorer Sport Offered by: Auto ...,il,38.802269,-90.673649,2021-04-25T12:13:13-0500,high
6922,7310766348,https://greensboro.craigslist.org/ctd/d/high-p...,greensboro,https://greensboro.craigslist.org,3999,2001.0,honda,civic,NaN,95674.0,NaN,NaN,https://images.craigslist.org/01212_hrL1gYZLbs...,Vann York Bargain Cars Call Sales at336-628-88...,nc,35.942696,-80.034679,2021-04-22T08:29:39-0400,low
6933,7311954478,https://slo.craigslist.org/ctd/d/templeton-201...,san luis obispo,https://slo.craigslist.org,28991,2018.0,chevrolet,express,gas,40238.0,clean,NaN,https://images.craigslist.org/01414_jnE9CxLsEn...,2018 Chevrolet Chevy Express 2500 Work Van ...,ca,35.581556,-120.698513,2021-04-24T10:40:55-0700,high
7018,7311616552,https://easttexas.craigslist.org/ctd/d/richard...,tyler / east TX,https://easttexas.craigslist.org,21999,2015.0,lexus,is,gas,66295.0,clean,NaN,https://images.craigslist.org/00e0e_gpfrBxDNfL...,2015 Lexus IS 250 ASE30L/GSE31L/GSE36L/GSE37L ...,tx,32.944193,-96.741595,2021-04-23T17:27:59-0500,medium
7196,7307751569,https://ocala.craigslist.org/ctd/d/kissimmee-2...,ocala,https://ocala.craigslist.org,18500,2020.0,hyundai,elantra,gas,5115.0,clean,NaN,https://images.craigslist.org/00J0J_65hDZvLxFX...,2020 Hyundai Elantra Limited Offered by: W...,fl,28.329026,-81.404237,2021-04-16T12:11:35-0400,medium
7751,7311607084,https://southjersey.craigslist.org/ctd/d/maple...,south jersey,https://southjersey.craigslist.org,27499,2019.0,lexus,ux,gas,16576.0,clean,NaN,https://images.craigslist.org/00R0R_hrj0btTe5R...,2019 Lexus UX 200 Base Offered by: VIP Aut...,nj,39.938023,-74.971461,2021-04-23T18:08:04-0400,high
8019,7303721685,https://poconos.craigslist.org/ctd/d/chesterfi...,poconos,https://poconos.craigslist.org,9499,2012.0,mini,cooper s countryman,gas,116854.0,clean,NaN,https://images.craigslist.org/01111_bOO9FFof1L...,2012 Mini Countryman S ALL4 Offered by: Ca...,pa,40.135190,-74.703570,2021-04-08T13:11:31-0400,low
8293,7315344895,https://slo.craigslist.org/ctd/d/templeton-201...,san luis obispo,https://slo.craigslist.org,16491,2012.0,ford,f-150,gas,119689.0,clean,NaN,https://images.craigslist.org/00I0I_hgsnr1wm1f...,2012 Ford F-150 F150 F 150 Offered by: Pas...,ca,35.581556,-120.698513,2021-05-01T09:25:34-0700,medium
8722,7316880026,https://houston.craigslist.org/ctd/d/houston-2...,houston,https://houston.craigslist.org,9491,2012.0,ford,mustang,gas,97947.0,clean,NaN,https://images.craigslist.org/00j0j_3FFSCVEb7v...,2012 Ford Mustang V6 Coupe Offered by: Hou...,tx,29.721560,-95.524841,2021-05-04T14:14:45-0500,low
9040,7316768908,https://portland.craigslist.org/clc/ctd/d/glad...,portland,https://portland.craigslist.org,25881,2020.0,nissan,leaf,electric,608.0,clean,NaN,https://images.craigslist.org/00o0o_gX4sj0dIcC...,2020 Nissan Leaf SV Offered by: Toyota of ...,or,45.381450,-122.606475,2021-05-04T09:21:15-0700,high
9345,7312061144,https://fortmyers.craigslist.org/lee/ctd/d/for...,ft myers / SW florida,https://fortmyers.craigslist.org,13000,2017.0,jeep,patriot,gas,37398.0,clean,NaN,https://images.craigslist.org/00m0m_1awSQ4PROX...,2017 Jeep Patriot Sport SE Offered by: EVE...,fl,26.498960,-81.819380,2021-04-24T16:37:38-0400,medium
9583,7304393640,https://anchorage.craigslist.org/ctd/d/anchora...,anchorage / mat-su,https://anchorage.craigslist.org,15995,2010.0,ford,e-350,gas,130626.0,clean,NaN,https://images.craigslist.org/00r0r_BeaE9Zxl4P...,2010 Ford E-Series Wagon E 350 SD 3dr Extended...,ak,61.161670,-149.863120,2021-04-09T13:27:13-0800,medium
9725,7312289741,https://maine.craigslist.org/ctd/d/methuen-201...,maine,https://maine.craigslist.org,19995,2017.0,harley-davidson,davidson flhx / street gl,gas,8719.0,clean,NaN,https://images.craigslist.org/00808_6vpXSxNnic...,2017 Harley-Davidson FLHX SCREAMING EAGLE STAG...,me,42.756205,-71.210258,2021-04-25T09:42:51-0400,medium
9805,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,NaN,95674.0,NaN,NaN,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low

In [20]:
len(df[df.transmission.notna()])#считает без НаН

9955

In [21]:
len(df[df.transmission.isna()])#считает с НаН

43

4. Обработайте пропуски, заполнив незаполненные значения коробки передач значением `other`, и сохраните изменения. Обратите внимание, что мы заполняем пропуски не самым популярным значением в выборке.

In [22]:
# Ваш код здесь
df.transmission = df.transmission.fillna('other')

5. Выведите для обновлённого датафрейма количество пропущенных значений для коробки передач.

In [23]:
# Допишите код
print("Количество пропущенных значений в transmission:", df.transmission.isna().sum())

Количество пропущенных значений в transmission: 0

In [24]:
len(df[df.transmission.notna()])

9998

### Задача 4. Обработка пропусков в широте и долготе
1. Выведите количество значений для широты, включая пропущенные значения. Обратите внимание на количество пропущенных значений.

In [25]:
# Ваш код здесь
df.lat.value_counts(dropna=False)

NaN          96
43.182400    88
33.779214    79
40.468785    73
33.786500    54
             ..
33.640251     1
39.942263     1
34.299800     1
44.472801     1
42.123900     1
Name: lat, Length: 5050, dtype: int64

2. Выведите описательные статистики широты в выборке.

In [26]:
# Ваш код здесь
df.lat.describe()

count    9902.000000
mean       38.594142
std         5.844895
min       -67.144243
25%        34.830368
50%        39.298522
75%        42.428070
max        64.947500
Name: lat, dtype: float64

3. Выведите записи, в которых широта не заполнена. Посмотрите внимательно на данные и обратите внимание, что если не заполнена широта, то не заполнена и долгота.

In [27]:
# Ваш код здесь
df[df.lat.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
118,7312692841,https://tricities.craigslist.org/ctd/d/bmw-ser...,tri-cities,https://tricities.craigslist.org,17998,2012.0,bmw,5 series,gas,62665.0,clean,automatic,https://images.craigslist.org/00909_57Xyuj8AJH...,2012 BMW 5 Series 535i M Sport Heat & Cool Sea...,tn,NaN,NaN,2021-04-26T04:28:35-0400,medium
126,7315526339,https://newjersey.craigslist.org/ctd/d/look-wh...,north jersey,https://newjersey.craigslist.org,22995,2014.0,bmw,7 series,gas,81085.0,clean,automatic,https://images.craigslist.org/00k0k_38TNTakyUf...,2014 BMW 7 Series 4dr Sdn 750Li xDrive AWD Aut...,nj,NaN,NaN,2021-05-01T17:49:09-0400,high
502,7308641593,https://winstonsalem.craigslist.org/ctd/d/ford...,winston-salem,https://winstonsalem.craigslist.org,20998,2016.0,ford,transit cargo,gas,123825.0,clean,automatic,https://images.craigslist.org/00101_gwJT4WBNRo...,2016 Ford Transit Cargo Vans Work Van High Roo...,nc,NaN,NaN,2021-04-18T04:43:46-0400,medium
567,7309282242,https://onslow.craigslist.org/ctd/d/mercedes-b...,jacksonville,https://onslow.craigslist.org,10810,2014.0,mercedes-benz,c-class,gas,124476.0,clean,automatic,https://images.craigslist.org/01414_6jNHxQwrKx...,2014 Mercedes Benz C Class C 250 Sport Coupe C...,nc,NaN,NaN,2021-04-19T12:06:28-0400,medium
692,7314847134,https://atlanta.craigslist.org/atl/ctd/d/2008-...,atlanta,https://atlanta.craigslist.org,17900,2008.0,toyota,tundra,gas,96000.0,clean,automatic,https://images.craigslist.org/01313_6u7l4KgvV4...,Description: 2008 Toyota Tundra 5...,ga,NaN,NaN,2021-04-30T12:09:49-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9154,7312710592,https://athensga.craigslist.org/ctd/d/bmw-x5-a...,athens,https://athensga.craigslist.org,14975,2013.0,bmw,x5,gas,97195.0,clean,automatic,https://images.craigslist.org/00i0i_kU6D0X9br2...,2013 BMW X5 xDrive35i Sport Activity Navigatio...,ga,NaN,NaN,2021-04-26T07:31:40-0400,medium
9408,7311736404,https://raleigh.craigslist.org/ctd/d/lexus-nx-...,raleigh / durham / CH,https://raleigh.craigslist.org,28998,2018.0,lexus,nx 300,gas,19863.0,clean,automatic,https://images.craigslist.org/00Q0Q_j7S3aRy6Sw...,2018 Lexus NX 300 Navigation Sunroof Bluetooth...,nc,NaN,NaN,2021-04-24T00:54:33-0400,high
9650,7315596665,https://newjersey.craigslist.org/ctd/d/wow-201...,north jersey,https://newjersey.craigslist.org,16495,2013.0,jeep,grand cherokee,other,90878.0,clean,automatic,https://images.craigslist.org/00v0v_awwo3NjD7Q...,2013 Jeep Grand Cherokee 4WD 4dr Laredo Automa...,nj,NaN,NaN,2021-05-01T20:53:57-0400,medium
9668,7308677951,https://myrtlebeach.craigslist.org/ctd/d/ford-...,myrtle beach,https://myrtlebeach.craigslist.org,33647,2015.0,ford,f-250 super duty,diesel,153524.0,clean,automatic,https://images.craigslist.org/00f0f_1c0aGXmmCL...,2015 Ford F250 4x4 Truck Diesel Pickup Trucks ...,sc,NaN,NaN,2021-04-18T08:43:25-0400,high
9915,7312622931,https://cincinnati.craigslist.org/cto/d/2005-d...,cincinnati,https://cincinnati.craigslist.org,7999,2005.0,ford,excursion 2005,diesel,210000.0,clean,automatic,https://images.craigslist.org/00E0E_i9lrp2qCVK...,Largest sport utility vehicle ever made in the...,oh,NaN,NaN,2021-04-25T21:12:31-0400,low

4. Необходимо убедиться, что долгота не заполнена только тогда, когда не заполнена широта. Выведите количество значений для долготы, включая пропущенные значения.

In [28]:
# Ваш код здесь
df.long.isna().sum()

96

In [29]:
df.long.value_counts(dropna=False)

 NaN          96
-84.112200    88
-84.411811    79
-74.281707    73
-84.445400    54
              ..
-82.527995     1
-97.031100     1
-85.806306     1
-78.625588     1
-79.189500     1
Name: long, Length: 5083, dtype: int64

5. Выведите количество значений, в которых не заполнена или широта, или долгота.

In [30]:
# Ваш код здесь
(df.long.isna() | df.lat.isna()).sum()

96

6. Обработайте пропуски, удалив записи, в которых широта или долгота не заполнены, и сохраните обновлённый датафрейм, а также выведите первые пять записей.

In [31]:
# Ваш код здесь
df = df[~(df.long.isna() | df.lat.isna())]
df.shape

(9902, 19)

7. Ещё раз выведите количество полностью заполненных объектов и их процент из всей выборки. Оставшиеся пропуски вы заполните позднее.

In [32]:
# Ваш код здесь
print_useful_rows_info(df)

Количество полностью заполненных объектов из всей выборки: 9543
Процент полностью заполненных объектов из всей выборки: 96.37

In [33]:
len(df.dropna())

9543

In [34]:
len(df)

9902

8. Сохраните получившийся датафрейм в файл `df_clean_upd.csv` для дальнейшего использования, индекс не сохраняйте.

In [35]:
df.to_csv('data/df_clean_upd.csv', index=False)

|

|

|

|

|

|

|

|

|

|

|

|

|

|

|

|

|

|

**Ответы для самостоятельной проверки**

### Задача 1.

In [ ]:
import pandas as pd

In [ ]:
# 1

df = pd.read_csv('data/df_clean.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442.0,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023.0,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048.0,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291.0,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000.0,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium

In [ ]:
# 2

def print_useful_rows_info(df):
    print('Количество полностью заполненных объектов из всей выборки:', len(df.dropna()))
    print('Процент полностью заполненных объектов из всей выборки:', round(len(df.dropna()) / len(df) * 100, 2))
    
print_useful_rows_info(df)

Количество полностью заполненных объектов из всей выборки: 9507
Процент полностью заполненных объектов из всей выборки: 95.07

In [ ]:
# 3

missing_values = ((df.isna().sum() / len(df)) * 100).sort_values(ascending=False)
print('Процент пропущенных значений:\n', missing_values)

Процент пропущенных значений:
 title_status      1.66
model             1.28
long              0.98
lat               0.98
fuel              0.63
transmission      0.45
year              0.36
image_url         0.02
posting_date      0.02
description       0.02
id                0.00
state             0.00
odometer          0.00
url               0.00
manufacturer      0.00
price             0.00
region_url        0.00
region            0.00
price_category    0.00
dtype: float64

In [ ]:
# 4

missing_columns = missing_values[missing_values.values > 0].index.tolist()
missing_columns

['title_status',
 'model',
 'long',
 'lat',
 'fuel',
 'transmission',
 'year',
 'image_url',
 'posting_date',
 'description']

### Задача 2.

In [ ]:
# 1

df.posting_date.value_counts(dropna=False)

NaN                         2
2021-04-28T13:55:19-0400    2
2021-05-02T15:50:49-0400    2
2021-04-29T21:11:29-0400    2
2021-04-30T15:02:51-0400    2
                           ..
2021-04-04T22:35:33-0500    1
2021-05-01T11:38:16-0700    1
2021-05-03T14:57:43-0600    1
2021-04-30T11:41:23-0400    1
2021-04-15T10:51:04-0500    1
Name: posting_date, Length: 9958, dtype: int64

In [ ]:
# 2

df.posting_date.describe()

count                         9998
unique                        9957
top       2021-04-05T09:41:14-0400
freq                             2
Name: posting_date, dtype: object

In [ ]:
# 3

df[df.posting_date.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
6728,7315259025,https://nh.craigslist.org/cto/d/manchester-201...,new hampshire,https://nh.craigslist.org,3750,NaN,other,NaN,NaN,95674.0,NaN,NaN,NaN,NaN,nh,NaN,NaN,NaN,low
9388,7208549803,https://bellingham.craigslist.org/ctd/d/bellin...,bellingham,https://bellingham.craigslist.org,11999,NaN,other,NaN,NaN,95674.0,NaN,NaN,NaN,NaN,wa,NaN,NaN,NaN,medium

In [ ]:
# 4

df = df[df.posting_date.notna()]

Количество пропущенных значений в posting_date: 0

In [ ]:
# 5

print("Количество пропущенных значений в posting_date:", df.posting_date.isna().sum())

### Задача 3.

In [ ]:
# 1

df.transmission.value_counts(dropna=False)

automatic    7700
other        1624
manual        631
NaN            43
Name: transmission, dtype: int64

In [ ]:
# 2

df.transmission.describe()

count          9955
unique            3
top       automatic
freq           7700
Name: transmission, dtype: object

In [ ]:
# 3

df[df.transmission.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
111,7305109580,https://grandrapids.craigslist.org/ctd/d/comst...,grand rapids,https://grandrapids.craigslist.org,12750,2013.0,lexus,es,gas,109382.0,clean,NaN,https://images.craigslist.org/00n0n_kACT1l7OCN...,2013 Lexus ES 350 4dr Sdn Offered by: Auto...,mi,43.059210,-85.688970,2021-04-11T09:41:58-0400,medium
112,7314951119,https://southjersey.craigslist.org/ctd/d/chest...,south jersey,https://southjersey.craigslist.org,18199,2012.0,jeep,wrangler,other,130174.0,clean,NaN,https://images.craigslist.org/00I0I_gRmuXmqil1...,2012 Jeep Wrangler Unlimited Sport 4WD Off...,nj,40.135190,-74.703570,2021-04-30T14:58:56-0400,medium
817,7308021604,https://southjersey.craigslist.org/ctd/d/maple...,south jersey,https://southjersey.craigslist.org,11999,2015.0,honda,civic,gas,79797.0,clean,NaN,https://images.craigslist.org/00b0b_aCqgRZ7sAx...,2015 Honda Civic EX Offered by: VIP Auto O...,nj,39.938023,-74.971461,2021-04-16T19:46:55-0400,medium
931,7314781483,https://nh.craigslist.org/ctd/d/plaistow-2018-...,new hampshire,https://nh.craigslist.org,64990,2018.0,ram,3500,other,8853.0,clean,NaN,https://images.craigslist.org/00000_iHpXs2BVmN...,2018 RAM Ram Chassis 3500 Short Wheelbase (Dua...,nh,42.834977,-71.107791,2021-04-30T10:15:30-0400,high
970,7315044723,https://poconos.craigslist.org/ctd/d/chesterfi...,poconos,https://poconos.craigslist.org,22699,2014.0,jeep,wrangler,gas,110493.0,clean,NaN,https://images.craigslist.org/00M0M_aFDXWIfug9...,2014 Jeep Wrangler Unlimited Sport 4WD Off...,pa,40.135190,-74.703570,2021-04-30T17:46:04-0400,high
1156,7311083008,https://greenville.craigslist.org/ctd/d/greenv...,greenville / upstate,https://greenville.craigslist.org,9998,2013.0,volkswagen,jetta,diesel,96115.0,clean,NaN,https://images.craigslist.org/00F0F_9oq0KNmZIM...,2013 VOLKSWAGEN JETTA TDI Highline Offered...,sc,34.832550,-82.368350,2021-04-22T17:55:57-0400,medium
1349,7303942891,https://wenatchee.craigslist.org/ctd/d/everett...,wenatchee,https://wenatchee.craigslist.org,4995,2005.0,honda,pilot,gas,261591.0,clean,NaN,https://images.craigslist.org/00S0S_aASnH27HDH...,2005 Honda Pilot EX Offered by: Corn Motor...,wa,47.912956,-122.235725,2021-04-08T16:52:48-0700,low
1715,7310344536,https://roanoke.craigslist.org/ctd/d/roanoke-2...,roanoke,https://roanoke.craigslist.org,3995,2007.0,ford,mustang,gas,159342.0,clean,NaN,https://images.craigslist.org/00J0J_6BuTyEWqNQ...,2007 Ford Mustang V6 Deluxe Coupe Offered ...,va,37.335355,-79.859385,2021-04-21T11:30:46-0400,low
1914,7307857568,https://fortmyers.craigslist.org/lee/ctd/d/for...,ft myers / SW florida,https://fortmyers.craigslist.org,17000,2012.0,jeep,grand cherokee,gas,116079.0,clean,NaN,https://images.craigslist.org/00000_gqxck1dkEu...,2012 Jeep Grand Cherokee Limited Offered b...,fl,26.498960,-81.819380,2021-04-16T14:46:41-0400,medium
2023,7314592581,https://pueblo.craigslist.org/ctd/d/pueblo-200...,pueblo,https://pueblo.craigslist.org,8494,2004.0,ford,ranger,gas,156969.0,clean,NaN,https://images.craigslist.org/01212_6ixSUy4WCq...,2004 Ford Ranger Offered by: Discount Moto...,co,38.298339,-104.616024,2021-04-29T17:30:13-0600,low
2072,7307459834,https://tallahassee.craigslist.org/ctd/d/ocala...,tallahassee,https://tallahassee.craigslist.org,22900,2013.0,ford,f-450,other,225804.0,clean,NaN,https://images.craigslist.org/00Y0Y_73hcVVn32A...,2013 Ford F-450 Super Duty 4X2 4dr SuperCab 16...,fl,29.230860,-82.149150,2021-04-15T18:47:10-0400,high
2078,7314485544,https://stlouis.craigslist.org/ctd/d/saint-pet...,"st louis, MO",https://stlouis.craigslist.org,15891,2019.0,nissan,sentra,gas,90811.0,clean,NaN,https://images.craigslist.org/00T0T_2tloqlG3YB...,2019 Nissan Sentra SV Offered by: Auto Pla...,il,38.802269,-90.673649,2021-04-29T14:55:20-0500,medium
2129,7302733118,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,14700,2016.0,ford,fusion,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00O0O_fkFRDDi4yq...,Car Starz Call Sales at 717-401-4221 2016 Ford...,pa,41.261540,-78.704520,2021-04-06T14:39:29-0400,medium
2627,7314386590,https://roanoke.craigslist.org/ctd/d/roanoke-2...,roanoke,https://roanoke.craigslist.org,7995,2013.0,nissan,altima,gas,87004.0,clean,NaN,https://images.craigslist.org/00E0E_T1UmvdZBIq...,2013 Nissan Altima 2.5 SL Offered by: Blue...,va,37.335355,-79.859385,2021-04-29T13:05:26-0400,low
3192,7307686006,https://cincinnati.craigslist.org/ctd/d/newpor...,cincinnati,https://cincinnati.craigslist.org,7995,2012.0,chevrolet,volt,hybrid,72205.0,clean,NaN,https://images.craigslist.org/00Y0Y_l66xSh7dIq...,2012 Chevrolet Chevy Volt Premium Offered ...,oh,39.002570,-84.423424,2021-04-16T10:31:31-0400,low
3551,7310989457,https://oklahomacity.craigslist.org/ctd/d/fort...,oklahoma city,https://oklahomacity.craigslist.org,10495,2016.0,subaru,outback,gas,205315.0,clean,NaN,https://images.craigslist.org/00909_iyoxNVG6Hv...,Se Habla Español! This GORGEOUS Subaru Outback...,ok,39.029900,-96.839600,2021-04-22T14:06:51-0500,medium
3814,7314143519,https://boise.craigslist.org/ctd/d/nampa-1971-...,boise,https://boise.craigslist.org,10395,1971.0,other,American LaFrance Fire Truck,NaN,78974.0,clean,NaN,https://images.craigslist.org/00909_aLVPntLOWj...,"1971 American LaFrance Fire Truck - $10,395....",id,43.593700,-116.536000,2021-04-28T19:02:38-0600,medium
3821,7314284239,https://gainesville.craigslist.org/ctd/d/kissi...,gainesville,https://gainesville.craigslist.org,12600,2012.0,lexus,is,gas,119123.0,clean,NaN,https://images.craigslist.org/00a0a_iLNqrX7M6C...,2012 Lexus IS 250 RWD Offered by: WE ARE O...,fl,28.329026,-81.404237,2021-04-29T10:05:17-0400,medium
3938,7313340095,https://flint.craigslist.org/ctd/d/burton-2018...,flint,https://flint.craigslist.org,8999,2018.0,nissan,sentra,gas,100502.0,clean,NaN,https://images.craigslist.org/01313_1Otgvohan8...,2018 NISSAN SENTRA SV Offered by: Tom's Di...,mi,43.004529,-83.635055,2021-04-27T11:36:15-0400,low
4087,7309751102,https://providence.craigslist.org/ctd/d/hookse...,rhode island,https://providence.craigslist.org,29888,2015.0,jeep,wrangler,gas,79873.0,clean,NaN,https://images.craigslist.org/00r0r_3nZoSFWLjf...,2015 Jeep Wrangler Rubicon 4WD Offered by:...,ri,43.066264,-71.447000,2021-04-20T09:32:59-0400,high
5081,7316685506,https://tampa.craigslist.org/hil/ctd/d/brandon...,tampa bay area,https://tampa.craigslist.org,16991,2016.0,ford,mustang,gas,81028.0,clean,NaN,https://images.craigslist.org/00q0q_ff4BI4TwI4...,2016 Ford Mustang EcoBoost Offered by: Bra...,fl,27.946392,-82.342089,2021-05-04T10:01:03-0400,medium
5260,7307388962,https://medford.craigslist.org/ctd/d/medford-2...,medford-ashland,https://medford.craigslist.org,14984,2010.0,ford,expedition,NaN,128975.0,NaN,NaN,https://images.craigslist.org/00B0B_aSYu1CvWOQ...,2010 Ford Expedition Eddie Bauer Sport Utility...,or,42.329925,-122.875811,2021-04-15T13:28:27-0700,medium
5320,7315518091,https://inlandempire.craigslist.org/ctd/d/font...,inland empire,https://inlandempire.craigslist.org,20775,2012.0,gmc,yukon,gas,104908.0,clean,NaN,https://images.craigslist.org/00y0y_jYD9hosoC3...,2012 GMC Yukon SLT Offered by: R & B AUTOS...,ca,34.107223,-117.455322,2021-05-01T14:30:28-0700,medium
5475,7303944212,https://yakima.craigslist.org/ctd/d/everett-20...,yakima,https://yakima.craigslist.org,7995,2013.0,dodge,grand caravan,gas,144401.0,clean,NaN,https://images.craigslist.org/00e0e_gr1IsBb5XA...,2013 Dodge Grand Caravan SE Offered by: Co...,wa,47.912956,-122.235725,2021-04-08T16:56:02-0700,low
5491,7302829978,https://greenville.craigslist.org/ctd/d/greenv...,greenville / upstate,https://greenville.craigslist.org,12988,2016.0,jeep,compass,gas,129674.0,clean,NaN,https://images.craigslist.org/00d0d_lHeM5HIRyZ...,2016 JEEP COMPASS 4X4 LATITUDE Offered by:...,sc,34.801450,-82.426210,2021-04-06T17:21:49-0400,medium
6172,7305971655,https://lancaster.craigslist.org/ctd/d/brockpo...,lancaster,https://lancaster.craigslist.org,7600,2012.0,jeep,patriot,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00909_hw8K8SHtsk...,Car Starz Call Sales at 717-401-4221 2012 Jeep...,pa,41.261540,-78.704520,2021-04-12T21:08:22-0400,low
6682,7303882218,https://chico.craigslist.org/ctd/d/sacramento-...,chico,https://chico.craigslist.org,27995,2018.0,ford,f-150,gas,72005.0,clean,NaN,https://images.craigslist.org/00Z0Z_eRA2RnvAhM...,2018 Ford F-150 F150 F 150 XL 2WD SuperCrew 5....,ca,38.611927,-121.423118,2021-04-08T14:42:05-0700,high
6757,7308278778,https://lincoln.craigslist.org/ctd/d/fort-rile...,lincoln,https://lincoln.craigslist.org,17495,2013.0,jeep,grand cherokee,gas,119275.0,clean,NaN,https://images.craigslist.org/00z0z_hH9cJEl2uw...,Se Habla Español! This GORGEOUS Jeep Grand Che...,ne,39.029900,-96.839600,2021-04-17T11:07:19-0500,medium
6817,7310860252,https://charlotte.craigslist.org/ctd/d/greensb...,charlotte,https://charlotte.craigslist.org,6998,2008.0,honda,civic cpe,NaN,95674.0,NaN,NaN,https://images.craigslist.org/00l0l_3evmKC5YBJ...,2008 Honda Civic Cpe 2dr Auto EX-L Oak Ridge ...,nc,36.129540,-79.957520,2021-04-22T11:41:26-0400,low
6851,7312392950,https://stlouis.craigslist.org/ctd/d/saint-pet...,"st louis, MO",https://stlouis.craigslist.org,24995,2015.0,ford,explorer,gas,101241.0,clean,NaN,https://images.craigslist.org/00B0B_e2X7o0yUFs...,2015 Ford Explorer Sport Offered by: Auto ...,il,38.802269,-90.673649,2021-04-25T12:13:13-0500,high
6922,7310766348,https://greensboro.craigslist.org/ctd/d/high-p...,greensboro,https://greensboro.craigslist.org,3999,2001.0,honda,civic,NaN,95674.0,NaN,NaN,https://images.craigslist.org/01212_hrL1gYZLbs...,Vann York Bargain Cars Call Sales at336-628-88...,nc,35.942696,-80.034679,2021-04-22T08:29:39-0400,low
6933,7311954478,https://slo.craigslist.org/ctd/d/templeton-201...,san luis obispo,https://slo.craigslist.org,28991,2018.0,chevrolet,express,gas,40238.0,clean,NaN,https://images.craigslist.org/01414_jnE9CxLsEn...,2018 Chevrolet Chevy Express 2500 Work Van ...,ca,35.581556,-120.698513,2021-04-24T10:40:55-0700,high
7018,7311616552,https://easttexas.craigslist.org/ctd/d/richard...,tyler / east TX,https://easttexas.craigslist.org,21999,2015.0,lexus,is,gas,66295.0,clean,NaN,https://images.craigslist.org/00e0e_gpfrBxDNfL...,2015 Lexus IS 250 ASE30L/GSE31L/GSE36L/GSE37L ...,tx,32.944193,-96.741595,2021-04-23T17:27:59-0500,medium
7196,7307751569,https://ocala.craigslist.org/ctd/d/kissimmee-2...,ocala,https://ocala.craigslist.org,18500,2020.0,hyundai,elantra,gas,5115.0,clean,NaN,https://images.craigslist.org/00J0J_65hDZvLxFX...,2020 Hyundai Elantra Limited Offered by: W...,fl,28.329026,-81.404237,2021-04-16T12:11:35-0400,medium
7751,7311607084,https://southjersey.craigslist.org/ctd/d/maple...,south jersey,https://southjersey.craigslist.org,27499,2019.0,lexus,ux,gas,16576.0,clean,NaN,https://images.craigslist.org/00R0R_hrj0btTe5R...,2019 Lexus UX 200 Base Offered by: VIP Aut...,nj,39.938023,-74.971461,2021-04-23T18:08:04-0400,high
8019,7303721685,https://poconos.craigslist.org/ctd/d/chesterfi...,poconos,https://poconos.craigslist.org,9499,2012.0,mini,cooper s countryman,gas,116854.0,clean,NaN,https://images.craigslist.org/01111_bOO9FFof1L...,2012 Mini Countryman S ALL4 Offered by: Ca...,pa,40.135190,-74.703570,2021-04-08T13:11:31-0400,low
8293,7315344895,https://slo.craigslist.org/ctd/d/templeton-201...,san luis obispo,https://slo.craigslist.org,16491,2012.0,ford,f-150,gas,119689.0,clean,NaN,https://images.craigslist.org/00I0I_hgsnr1wm1f...,2012 Ford F-150 F150 F 150 Offered by: Pas...,ca,35.581556,-120.698513,2021-05-01T09:25:34-0700,medium
8722,7316880026,https://houston.craigslist.org/ctd/d/houston-2...,houston,https://houston.craigslist.org,9491,2012.0,ford,mustang,gas,97947.0,clean,NaN,https://images.craigslist.org/00j0j_3FFSCVEb7v...,2012 Ford Mustang V6 Coupe Offered by: Hou...,tx,29.721560,-95.524841,2021-05-04T14:14:45-0500,low
9040,7316768908,https://portland.craigslist.org/clc/ctd/d/glad...,portland,https://portland.craigslist.org,25881,2020.0,nissan,leaf,electric,608.0,clean,NaN,https://images.craigslist.org/00o0o_gX4sj0dIcC...,2020 Nissan Leaf SV Offered by: Toyota of ...,or,45.381450,-122.606475,2021-05-04T09:21:15-0700,high
9345,7312061144,https://fortmyers.craigslist.org/lee/ctd/d/for...,ft myers / SW florida,https://fortmyers.craigslist.org,13000,2017.0,jeep,patriot,gas,37398.0,clean,NaN,https://images.craigslist.org/00m0m_1awSQ4PROX...,2017 Jeep Patriot Sport SE Offered by: EVE...,fl,26.498960,-81.819380,2021-04-24T16:37:38-0400,medium
9583,7304393640,https://anchorage.craigslist.org/ctd/d/anchora...,anchorage / mat-su,https://anchorage.craigslist.org,15995,2010.0,ford,e-350,gas,130626.0,clean,NaN,https://images.craigslist.org/00r0r_BeaE9Zxl4P...,2010 Ford E-Series Wagon E 350 SD 3dr Extended...,ak,61.161670,-149.863120,2021-04-09T13:27:13-0800,medium
9725,7312289741,https://maine.craigslist.org/ctd/d/methuen-201...,maine,https://maine.craigslist.org,19995,2017.0,harley-davidson,davidson flhx / street gl,gas,8719.0,clean,NaN,https://images.craigslist.org/00808_6vpXSxNnic...,2017 Harley-Davidson FLHX SCREAMING EAGLE STAG...,me,42.756205,-71.210258,2021-04-25T09:42:51-0400,medium
9805,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,NaN,95674.0,NaN,NaN,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low

In [ ]:
# 4

df.transmission = df.transmission.fillna('other')

In [ ]:
# 5

print("Количество пропущенных значений в transmission:", df.transmission.isna().sum())

Количество пропущенных значений в transmission: 0

### Задача 4.

In [ ]:
# 1

df.lat.value_counts(dropna=False)

NaN          96
43.182400    88
33.779214    79
40.468785    73
33.786500    54
             ..
34.925100     1
40.032600     1
42.528000     1
41.595393     1
34.799530     1
Name: lat, Length: 5050, dtype: int64

In [ ]:
# 2

df.lat.describe()

count    9902.000000
mean       38.594142
std         5.844895
min       -67.144243
25%        34.830368
50%        39.298522
75%        42.428070
max        64.947500
Name: lat, dtype: float64

In [ ]:
# 3

df[df.lat.isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category
118,7312692841,https://tricities.craigslist.org/ctd/d/bmw-ser...,tri-cities,https://tricities.craigslist.org,17998,2012.0,bmw,5 series,gas,62665.0,clean,automatic,https://images.craigslist.org/00909_57Xyuj8AJH...,2012 BMW 5 Series 535i M Sport Heat & Cool Sea...,tn,NaN,NaN,2021-04-26T04:28:35-0400,medium
126,7315526339,https://newjersey.craigslist.org/ctd/d/look-wh...,north jersey,https://newjersey.craigslist.org,22995,2014.0,bmw,7 series,gas,81085.0,clean,automatic,https://images.craigslist.org/00k0k_38TNTakyUf...,2014 BMW 7 Series 4dr Sdn 750Li xDrive AWD Aut...,nj,NaN,NaN,2021-05-01T17:49:09-0400,high
502,7308641593,https://winstonsalem.craigslist.org/ctd/d/ford...,winston-salem,https://winstonsalem.craigslist.org,20998,2016.0,ford,transit cargo,gas,123825.0,clean,automatic,https://images.craigslist.org/00101_gwJT4WBNRo...,2016 Ford Transit Cargo Vans Work Van High Roo...,nc,NaN,NaN,2021-04-18T04:43:46-0400,medium
567,7309282242,https://onslow.craigslist.org/ctd/d/mercedes-b...,jacksonville,https://onslow.craigslist.org,10810,2014.0,mercedes-benz,c-class,gas,124476.0,clean,automatic,https://images.craigslist.org/01414_6jNHxQwrKx...,2014 Mercedes Benz C Class C 250 Sport Coupe C...,nc,NaN,NaN,2021-04-19T12:06:28-0400,medium
692,7314847134,https://atlanta.craigslist.org/atl/ctd/d/2008-...,atlanta,https://atlanta.craigslist.org,17900,2008.0,toyota,tundra,gas,96000.0,clean,automatic,https://images.craigslist.org/01313_6u7l4KgvV4...,Description: 2008 Toyota Tundra 5...,ga,NaN,NaN,2021-04-30T12:09:49-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9154,7312710592,https://athensga.craigslist.org/ctd/d/bmw-x5-a...,athens,https://athensga.craigslist.org,14975,2013.0,bmw,x5,gas,97195.0,clean,automatic,https://images.craigslist.org/00i0i_kU6D0X9br2...,2013 BMW X5 xDrive35i Sport Activity Navigatio...,ga,NaN,NaN,2021-04-26T07:31:40-0400,medium
9408,7311736404,https://raleigh.craigslist.org/ctd/d/lexus-nx-...,raleigh / durham / CH,https://raleigh.craigslist.org,28998,2018.0,lexus,nx 300,gas,19863.0,clean,automatic,https://images.craigslist.org/00Q0Q_j7S3aRy6Sw...,2018 Lexus NX 300 Navigation Sunroof Bluetooth...,nc,NaN,NaN,2021-04-24T00:54:33-0400,high
9650,7315596665,https://newjersey.craigslist.org/ctd/d/wow-201...,north jersey,https://newjersey.craigslist.org,16495,2013.0,jeep,grand cherokee,other,90878.0,clean,automatic,https://images.craigslist.org/00v0v_awwo3NjD7Q...,2013 Jeep Grand Cherokee 4WD 4dr Laredo Automa...,nj,NaN,NaN,2021-05-01T20:53:57-0400,medium
9668,7308677951,https://myrtlebeach.craigslist.org/ctd/d/ford-...,myrtle beach,https://myrtlebeach.craigslist.org,33647,2015.0,ford,f-250 super duty,diesel,153524.0,clean,automatic,https://images.craigslist.org/00f0f_1c0aGXmmCL...,2015 Ford F250 4x4 Truck Diesel Pickup Trucks ...,sc,NaN,NaN,2021-04-18T08:43:25-0400,high
9915,7312622931,https://cincinnati.craigslist.org/cto/d/2005-d...,cincinnati,https://cincinnati.craigslist.org,7999,2005.0,ford,excursion 2005,diesel,210000.0,clean,automatic,https://images.craigslist.org/00E0E_i9lrp2qCVK...,Largest sport utility vehicle ever made in the...,oh,NaN,NaN,2021-04-25T21:12:31-0400,low

In [ ]:
# 4

df.long.value_counts(dropna=False)

 NaN          96
-84.112200    88
-84.411811    79
-74.281707    73
-84.445400    54
              ..
-87.999100     1
-77.157326     1
-84.277765     1
-73.427371     1
-78.114100     1
Name: long, Length: 5083, dtype: int64

In [ ]:
# 5

(df.long.isna() | df.lat.isna()).sum()

96

In [ ]:
# 6

df = df[~(df.long.isna() | df.lat.isna())]
df.shape

In [ ]:
# 7

print_useful_rows_info(df)

Количество полностью заполненных объектов из всей выборки: 9543
Процент полностью заполненных объектов из всей выборки: 95.45

In [ ]:
# 8

df.to_csv('data/df_clean_upd.csv', index=False)